name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-29"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWM1MWU1ZGEtZWFmYi00ZTA2LWExZDAtMzFhMjkwNDBiOGRmIiwidGVuYW50X2lkIjoiMjdhYjBiYzJlMTkxNmEyN2Y4YmZhOGJlZTAzZjYzNTZkNmNkMTZlOTFjOWY0ZWQ3MjUwYWJkMWUzYTUyNDBhMyIsImludGVybmFsX3NlY3JldCI6IjkwNDc2OGJlLTA1NDctNGE5Ny05YTFkLWVmZjY3MWJiYjBmZCJ9.cJu9-Q00eG1iTeVk0kvhSgTgKPk6SVnQMsyZ62RtxrQ"
JWT_SECRET = "qazwsxedcrfvtgbyhnujmikolp"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1